### ISSUE TITLE
Lasso recipe not showing?

### ISSUE THREAD

**Issue by mbergfors** [BrewingCoder/BrewTools#2]
The Night vision glasses and mining portal seems to work fine, but the Lasso and Redstone clock don't (using JEI)? No recipe for either? I tried the old Extra Utilities recipe for giggles, but nope. Help?

**Comment by BrewingCoder** [comment]
Fixed in 1.2.13 --  Sorry about that; I totally forgot to copy that file over when I made my new branch.  It's up and approved on curseforge.

**Comment by BrewingCoder** [comment]
aaaaand.. .I just saw the mention of the redstone clock.  I guess I've one more build to push.

**Comment by BrewingCoder** [comment]
Really fixed in 1.2.14 this time :)  File is pending approval on curseforge.

**Comment by mbergfors** [comment]
Looks like you got it! Can confirm lasso is working perfectly. Thanks again for making it! Really one I was missing from the old days.  :)
